version: '3'

services:
  api:
    build: ../api
    ports:
      #only for testig, in release no port forward for api
      - '8000:80'
    volumes:
      - ./test_db/:/app/db_for_test

  proxy:
    image: nginx:latest
    ports:
      #only for testing, in release forward 443 to 443 with ssl certs on nginx
      - '80:80'
    volumes:
      - ../front-end/build/:/front-end/build/
      - ../proxy/speedrun-proxy.conf:/etc/nginx/conf.d/default.conf
